// Production motherboard and GHDL-translated T80. External memory is supplied
// by C++; no SDRAM controller, cartridge mux, firmware, or physical device model.
module ssm_provider_top (
 input clk, reset, irq, extra_wait, plus_mode,
 input [7:0] cpu_din,
 output [15:0] cpu_addr,
 output [7:0] cpu_dout,
 output [22:0] mem_addr,
 output mem_rd, mem_wr, romen, cpu_halt_n, iorq, mreq, rd, m1,
 output ssm_m1_fetch,
 output [7:0] ssm_bus_data,
 output [20:0] ssm_sync_observation,
 output wait_n,
 output [15:0] last_code,
 output [31:0] event_count,
 output event_stb
);
 reg [1:0] div = 0;
 reg ce_16 = 0;
 always @(posedge clk) begin
   div <= div + 1'b1;
   ce_16 <= div == 0;
 end
 Amstrad_motherboard mb (
 .reset(reset),
 .clk(clk),
 .ce_16(ce_16),
 .plus_mode(plus_mode),
 .plus_unlocked('0),
 .plus_ram_128k('0),
 .plus_has_fdc('0),
 .plus_has_tape('0),
 .plus_mem_wait(extra_wait),
 .plus_aspage_on('0),
 .plus_asic_dout(),
 .plus_asic_rd(),
 .plus_vec_byte(),
 .plus_vec_valid(),
 .joy1('0),
 .joy2('0),
 .right_shift_mod('0),
 .keypad_mod('0),
 .ps2_key('0),
 .ps2_mouse('0),
 .joy1_sel(),
 .joy2_sel(),
 .key_nmi(),
 .key_reset(),
 .Fn(),
 .ppi_jumpers(4'b1010),
 .crtc_type('0),
 .sync_filter('0),
 .no_wait('0),
 .sna_load('0),
 .sna_cpu_dir('0),
 .sna_crtc_addr('0),
 .sna_crtc_regs('0),
 .sna_ga_inksel('0),
 .sna_ga_palette('0),
 .sna_ga_config('0),
 .sna_ram_config('0),
 .sna_rom_select('0),
 .sna_ppi_a('0),
 .sna_ppi_b('0),
 .sna_ppi_c('0),
 .sna_ppi_control('0),
 .sna_psg_addr('0),
 .sna_psg_regs('0),
 .sna_hold('0),
 .save_hold('0),
 .sna_hsync('0),
 .sna_dma_loop_cnt0('0),
 .sna_dma_loop_cnt1('0),
 .sna_dma_loop_cnt2('0),
 .sna_dma_loop_addr0('0),
 .sna_dma_loop_addr1('0),
 .sna_dma_loop_addr2('0),
 .sna_dma_pause_cnt0('0),
 .sna_dma_pause_cnt1('0),
 .sna_dma_pause_cnt2('0),
 .sna_dma_pause_presc0('0),
 .sna_dma_pause_presc1('0),
 .sna_dma_pause_presc2('0),
 .sna_crtc_hcc('0),
 .sna_crtc_line('0),
 .sna_crtc_raster('0),
 .sna_crtc_vta('0),
 .sna_crtc_hsw('0),
 .sna_crtc_vsw('0),
 .sna_crtc_vs('0),
 .sna_crtc_adj('0),
 .sna_ga_vsdelay('0),
 .sna_ga_intcnt('0),
 .sna_int_pending('0),
 .sna_plus_chunk('0),
 .plus_sna_wr('0),
 .plus_sna_addr('0),
 .plus_sna_data('0),
 .plus_asic_reset('0),
 .tape_in(1'b1),
 .tape_out(),
 .tape_motor(),
 .audio_l(),
 .audio_r(),
 .mode(),
 .red(),
 .green(),
 .blue(),
 .ssm_m1_fetch(ssm_m1_fetch),
 .ssm_bus_data(ssm_bus_data),
 .ssm_sync_observation(ssm_sync_observation),
 .hblank(),
 .vblank(),
 .hsync(),
 .vsync(),
 .field(),
 .raw_crt(),
 .pixel_vblank(),
 .vram_din('0),
 .vram_addr(),
 .rom_map('0),
 .ram64k('0),
 .mem_addr(mem_addr),
 .mem_rd(mem_rd),
 .mem_wr(mem_wr),
 .romen(romen),
 .phi_n(),
 .phi_en_n(),
 .phi_en_p(),
 .cpu_addr(cpu_addr),
 .cpu_dout(cpu_dout),
 .cpu_din(cpu_din),
 .iorq(iorq),
 .asic_iorq(),
 .mreq(mreq),
 .rd(rd),
 .wr(),
 .m1(m1),
 .io_bus_byte(),
 .ga_ready(),
 .irq(irq),
 .nmi('0),
 .cursor(),
 .snap_ga_inksel(),
 .snap_ga_border(),
 .snap_ga_inkr(),
 .snap_ga_hromen(),
 .snap_ga_lromen(),
 .snap_ga_mode(),
 .snap_ga_intcnt(),
 .snap_ga_hcnt(),
 .snap_ga_int_n(),
 .snap_crtc_addr(),
 .snap_crtc_regs(),
 .snap_crtc_hcc(),
 .snap_crtc_row(),
 .snap_crtc_line(),
 .snap_crtc_c5(),
 .snap_crtc_in_adj(),
 .snap_crtc_hsc(),
 .snap_crtc_hsync(),
 .snap_crtc_vsync_r(),
 .snap_crtc_vsw_elapsed(),
 .snap_mmu_rammap(),
 .snap_mmu_rampage(),
 .snap_mmu_rom_select_shadow(),
 .snap_ppi_porta_in(),
 .snap_ppi_portb_in(),
 .snap_ppi_opc_r(),
 .snap_ppi_mode(),
 .snap_psg_addr(),
 .snap_psg_regs(),
 .snap_printer_data(),
 .cpu_reg(),
 .cpu_insn_start(),
 .cpu_halt_n(cpu_halt_n)
 );
 assign wait_n = mb.CPU.WAIT_n;
 ssm_marker marker (
 .clk(clk), .reset(reset), .enable(1'b1),
 .m1_fetch(ssm_m1_fetch), .bus_data(ssm_bus_data),
 .sync_observation(ssm_sync_observation),
 .ce_pix(ce_16), .hsync(1'b0), .vsync(1'b0), .field(1'b0),
 .last_code(last_code), .event_count(event_count), .event_stb(event_stb),
 .dropped_count(), .ddram_addr(), .ddram_din(), .ddram_be(),
 .ddram_burstcnt(), .ddram_we(), .ddram_busy(1'b0)
 );
endmodule
